#!/bin/bash

echo "🚀 Простой деплой - без интерактивных шагов"
echo ""
echo "📋 Инструкция:"
echo ""
echo "1. Создайте репозиторий на GitHub:"
echo "   https://github.com/new"
echo "   Название: exchanger"
echo "   НЕ добавляйте README, .gitignore, license"
echo ""
echo "2. После создания репозитория, выполните:"
echo ""
echo "   git remote add origin https://github.com/YOUR_USERNAME/exchanger.git"
echo "   git branch -M main"
echo "   git push -u origin main"
echo ""
echo "3. Затем задеплойте через веб-интерфейсы:"
echo "   - Vercel: https://vercel.com"
echo "   - Railway: https://railway.app"
echo ""
echo "Подробная инструкция в файле: START_HERE.md"
